# -*- coding: utf-8 -*-
"""Martial Arts AI Coach

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mUjnlEAWLVm7KslWBPn43PcvFRHnMsTa
"""

!pip install google-generativeai

import os
os.environ["GOOGLE_API_KEY"] = "made this mistake once not again"

import os
import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold

# Set up the API
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

# System prompt - tells Gemini how to act as a coach
system_prompt = """You are an expert martial arts coach and mentor with decades of experience in boxing, Muay Thai, kickboxing, wrestling, and MMA.

Your job is to:
- Give personalized advice on techniques, form, and strategy
- Help diagnose and treat training injuries safely
- Provide mental game and mindset coaching
- Create training plans tailored to the fighter
- Answer questions about nutrition, recovery, and conditioning

Always be encouraging, realistic and motivating"""

# Initialize the model
# Changed model_name from 'gemini-1.5-flash' to 'gemini-pro'

# List available models and find one that supports generateContent
available_models = genai.list_models()
selected_model_name = None
for m in available_models:
    if "generateContent" in m.supported_generation_methods:
        selected_model_name = m.name
        break

if selected_model_name:
    print(f"Using model: {selected_model_name}")
    model = genai.GenerativeModel(
        model_name=selected_model_name,
        system_instruction=system_prompt,
        safety_settings={
            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
        }
    )
else:
    raise ValueError("No model supporting 'generateContent' found. Please check your API key and permissions.")

# Keep track of conversation history
conversation_history = []

def ask_coach(user_message):
    """Send a message to your AI coach and get a response"""

    # Add user message to history
    conversation_history.append({
        "role": "user",
        "parts": [user_message]
    })

    # Send to Gemini
    response = model.generate_content(
        contents=conversation_history,
        stream=False
    )

    # Get the response
    assistant_message = response.text

    # Add assistant response to history (so it remembers)
    conversation_history.append({
        "role": "model",
        "parts": [assistant_message]
    })

    return assistant_message
# INTERACTIVE CHAT MODE
print("🥊 Welcome to your AI Martial Arts Coach!")
print("Ask me anything about fighting, training, injuries, technique...")
print("Type 'exit' to quit\n")

while True:
    user_input = input("You: ").strip()

    if user_input.lower() == "exit":
        print("Coach: Great training session! Keep grinding! 💪")
        break

    if not user_input:
        print("(Please ask something)\n")
        continue

    print("Coach: ", end="", flush=True)
    response = ask_coach(user_input)
    print(response)
    print("\n" + "-" * 80 + "\n")

for question in questions:
    print(f"You: {question}")
    response = ask_coach(question)
    print(f"Coach: {response}\n")
    print("-" * 80 + "\n")
