{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "toc_visible": true,
      "authorship_tag": "ABX9TyPOte2jPp4tylaXd5kQ8agp",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Raghavrana01/mmaai/blob/main/Martial_Arts_AI_Coach.py.c\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install google-generativeai"
      ],
      "metadata": {
        "collapsed": true,
        "id": "FZ3UW_9qha6n"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "os.environ[\"GOOGLE_API_KEY\"] = \"AIzaSyB_AgN86Nd6UWjX75n2nwHJeYiETrRlVBw\""
      ],
      "metadata": {
        "id": "iV4iUbGNhsn9"
      },
      "execution_count": 20,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import google.generativeai as genai\n",
        "from google.generativeai.types import HarmCategory, HarmBlockThreshold\n",
        "\n",
        "# Set up the API\n",
        "genai.configure(api_key=os.environ[\"GOOGLE_API_KEY\"])\n",
        "\n",
        "# System prompt - tells Gemini how to act as a coach\n",
        "system_prompt = \"\"\"You are an expert martial arts coach and mentor with decades of experience in boxing, Muay Thai, kickboxing, wrestling, and MMA.\n",
        "\n",
        "Your job is to:\n",
        "- Give personalized advice on techniques, form, and strategy\n",
        "- Help diagnose and treat training injuries safely\n",
        "- Provide mental game and mindset coaching\n",
        "- Create training plans tailored to the fighter\n",
        "- Answer questions about nutrition, recovery, and conditioning\n",
        "\n",
        "Always be encouraging, realistic and motivating\"\"\"\n",
        "\n",
        "# Initialize the model\n",
        "# Changed model_name from 'gemini-1.5-flash' to 'gemini-pro'\n",
        "\n",
        "# List available models and find one that supports generateContent\n",
        "available_models = genai.list_models()\n",
        "selected_model_name = None\n",
        "for m in available_models:\n",
        "    if \"generateContent\" in m.supported_generation_methods:\n",
        "        selected_model_name = m.name\n",
        "        break\n",
        "\n",
        "if selected_model_name:\n",
        "    print(f\"Using model: {selected_model_name}\")\n",
        "    model = genai.GenerativeModel(\n",
        "        model_name=selected_model_name,\n",
        "        system_instruction=system_prompt,\n",
        "        safety_settings={\n",
        "            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,\n",
        "            HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,\n",
        "        }\n",
        "    )\n",
        "else:\n",
        "    raise ValueError(\"No model supporting 'generateContent' found. Please check your API key and permissions.\")\n",
        "\n",
        "# Keep track of conversation history\n",
        "conversation_history = []\n",
        "\n",
        "def ask_coach(user_message):\n",
        "    \"\"\"Send a message to your AI coach and get a response\"\"\"\n",
        "\n",
        "    # Add user message to history\n",
        "    conversation_history.append({\n",
        "        \"role\": \"user\",\n",
        "        \"parts\": [user_message]\n",
        "    })\n",
        "\n",
        "    # Send to Gemini\n",
        "    response = model.generate_content(\n",
        "        contents=conversation_history,\n",
        "        stream=False\n",
        "    )\n",
        "\n",
        "    # Get the response\n",
        "    assistant_message = response.text\n",
        "\n",
        "    # Add assistant response to history (so it remembers)\n",
        "    conversation_history.append({\n",
        "        \"role\": \"model\",\n",
        "        \"parts\": [assistant_message]\n",
        "    })\n",
        "\n",
        "    return assistant_message\n",
        "# INTERACTIVE CHAT MODE\n",
        "print(\"🥊 Welcome to your AI Martial Arts Coach!\")\n",
        "print(\"Ask me anything about fighting, training, injuries, technique...\")\n",
        "print(\"Type 'exit' to quit\\n\")\n",
        "\n",
        "while True:\n",
        "    user_input = input(\"You: \").strip()\n",
        "\n",
        "    if user_input.lower() == \"exit\":\n",
        "        print(\"Coach: Great training session! Keep grinding! 💪\")\n",
        "        break\n",
        "\n",
        "    if not user_input:\n",
        "        print(\"(Please ask something)\\n\")\n",
        "        continue\n",
        "\n",
        "    print(\"Coach: \", end=\"\", flush=True)\n",
        "    response = ask_coach(user_input)\n",
        "    print(response)\n",
        "    print(\"\\n\" + \"-\" * 80 + \"\\n\")\n",
        "\n",
        "for question in questions:\n",
        "    print(f\"You: {question}\")\n",
        "    response = ask_coach(question)\n",
        "    print(f\"Coach: {response}\\n\")\n",
        "    print(\"-\" * 80 + \"\\n\")"
      ],
      "metadata": {
        "collapsed": true,
        "id": "chBDgUl7h0RB"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import google.generativeai as genai\n",
        "from google.generativeai.types import HarmCategory, HarmBlockThreshold\n",
        "import os\n",
        "import json\n",
        "from datetime import datetime\n",
        "import time\n",
        "\n",
        "# Set up API\n",
        "genai.configure(api_key=os.environ.get(\"GOOGLE_API_KEY\"))\n",
        "\n",
        "# System prompt for the coach\n",
        "system_prompt = \"\"\"You are an expert martial arts coach and mentor with decades of experience in boxing, Muay Thai, kickboxing, wrestling, and MMA.\n",
        "\n",
        "Your job is to:\n",
        "- Give personalized advice on techniques, form, and strategy\n",
        "- Help diagnose and treat training injuries safely\n",
        "- Provide mental game and mindset coaching\n",
        "- Create training plans tailored to the fighter\n",
        "- Answer questions about nutrition, recovery, and conditioning\n",
        "\n",
        "Always be encouraging, realistic, and safety-conscious. Keep responses concise but detailed (2-4 paragraphs). If something requires a doctor, tell them to see one.\n",
        "\n",
        "IMPORTANT: The user may reference their training history from previous sessions. Use this context to give better, more personalized advice.\"\"\"\n",
        "\n",
        "# Initialize the model\n",
        "\n",
        "available_models = genai.list_models()\n",
        "selected_model_name = None\n",
        "for m in available_models:\n",
        "    if \"generateContent\" in m.supported_generation_methods:\n",
        "        selected_model_name = m.name\n",
        "        break\n",
        "\n",
        "\n",
        "# Training history file\n",
        "HISTORY_FILE = \"training_history.json\"\n",
        "\n",
        "def load_history():\n",
        "    \"\"\"Load training history from file\"\"\"\n",
        "    if os.path.exists(HISTORY_FILE):\n",
        "        try:\n",
        "            with open(HISTORY_FILE, 'r') as f:\n",
        "                return json.load(f)\n",
        "        except:\n",
        "            return []\n",
        "    return []\n",
        "\n",
        "def save_history(history):\n",
        "    \"\"\"Save training history to file\"\"\"\n",
        "    with open(HISTORY_FILE, 'w') as f:\n",
        "        json.dump(history, f, indent=2)\n",
        "\n",
        "def get_history_summary(history):\n",
        "    \"\"\"Create a summary of recent training sessions for context\"\"\"\n",
        "    if not history:\n",
        "        return \"No previous training history.\"\n",
        "\n",
        "    # Get last 5 sessions\n",
        "    recent_sessions = history[-5:]\n",
        "    summary = \"Recent training history:\\n\"\n",
        "\n",
        "    for i, session in enumerate(recent_sessions, 1):\n",
        "        date = session.get('date', 'Unknown date')\n",
        "        topics = session.get('topics', [])\n",
        "        summary += f\"\\n{i}. Session on {date}\\n\"\n",
        "        if topics:\n",
        "            summary += f\"   Topics discussed: {', '.join(topics[:3])}\\n\"\n",
        "\n",
        "    return summary\n",
        "\n",
        "def extract_topics(messages):\n",
        "    \"\"\"Extract main topics from conversation\"\"\"\n",
        "    topics = set()\n",
        "    martial_arts = ['boxing', 'muay thai', 'kickboxing', 'wrestling', 'mma', 'jiu jitsu', 'karate', 'taekwondo']\n",
        "    training_aspects = ['footwork', 'technique', 'injury', 'conditioning', 'mindset', 'nutrition', 'recovery',\n",
        "                       'strength', 'cardio', 'speed', 'power', 'defense', 'stance', 'combinations']\n",
        "\n",
        "    text = ' '.join([msg.get('content', '').lower() for msg in messages])\n",
        "\n",
        "    for art in martial_arts:\n",
        "        if art in text:\n",
        "            topics.add(art.title())\n",
        "\n",
        "    for aspect in training_aspects:\n",
        "        if aspect in text:\n",
        "            topics.add(aspect.title())\n",
        "\n",
        "    return list(topics)[:5]  # Return top 5 topics\n",
        "\n",
        "def main():\n",
        "    \"\"\"Main chat loop with history saving\"\"\"\n",
        "\n",
        "    # Load previous history\n",
        "    training_history = load_history()\n",
        "    conversation_history = []\n",
        "\n",
        "    print(\"🥊 Welcome to your AI Martial Arts Coach!\")\n",
        "    print(\"=\" * 60)\n",
        "\n",
        "    # Show history summary\n",
        "    if training_history:\n",
        "        print(\"\\n📋 Your Training History:\")\n",
        "        print(get_history_summary(training_history))\n",
        "    else:\n",
        "        print(\"\\n📋 This is your first session! Let's build your training foundation.\")\n",
        "\n",
        "    print(\"\\n\" + \"=\" * 60)\n",
        "    print(\"Ask me anything about fighting, training, injuries, technique...\")\n",
        "    print(\"Type 'exit' to quit | 'history' to see past sessions\")\n",
        "    print(\"=\" * 60 + \"\\n\")\n",
        "\n",
        "    while True:\n",
        "        try:\n",
        "            user_input = input(\"You: \").strip()\n",
        "\n",
        "            if user_input.lower() == \"exit\":\n",
        "                # Save session before exiting\n",
        "                if conversation_history:\n",
        "                    topics = extract_topics(conversation_history)\n",
        "                    session_data = {\n",
        "                        'date': datetime.now().strftime(\"%Y-%m-%d %H:%M\"),\n",
        "                        'messages_count': len(conversation_history),\n",
        "                        'topics': topics\n",
        "                    }\n",
        "                    training_history.append(session_data)\n",
        "                    save_history(training_history)\n",
        "                    print(f\"\\n✅ Session saved! ({len(conversation_history)} messages)\")\n",
        "\n",
        "                print(\"Coach: Great training session! Keep grinding! 💪\")\n",
        "                break\n",
        "\n",
        "            if user_input.lower() == \"history\":\n",
        "                if training_history:\n",
        "                    print(\"\\n📚 Full Training History:\")\n",
        "                    for i, session in enumerate(training_history, 1):\n",
        "                        date = session.get('date', 'Unknown')\n",
        "                        count = session.get('messages_count', '?')\n",
        "                        topics = ', '.join(session.get('topics', []))\n",
        "                        print(f\"\\n{i}. {date}\")\n",
        "                        print(f\"   Messages: {count}\")\n",
        "                        print(f\"   Topics: {topics}\")\n",
        "                    print()\n",
        "                else:\n",
        "                    print(\"No training history yet. Start chatting!\\n\")\n",
        "                continue\n",
        "\n",
        "            if not user_input:\n",
        "                print(\"(Please ask something)\\n\")\n",
        "                continue\n",
        "\n",
        "            # Add user message to conversation\n",
        "            conversation_history.append({\n",
        "                \"role\": \"user\",\n",
        "                \"parts\": [user_input]\n",
        "            })\n",
        "\n",
        "            # Show typing indicator\n",
        "            print(\"Coach: \", end=\"\", flush=True)\n",
        "\n",
        "            # Send to Gemini\n",
        "            response = model.generate_content(\n",
        "                contents=conversation_history,\n",
        "                stream=False\n",
        "            )\n",
        "\n",
        "            coach_response = response.text\n",
        "\n",
        "            # Add coach response to conversation\n",
        "            conversation_history.append({\n",
        "                \"role\": \"model\",\n",
        "                \"parts\": [coach_response]\n",
        "            })\n",
        "\n",
        "            print(coach_response)\n",
        "            print(\"\\n\" + \"-\" * 60 + \"\\n\")\n",
        "\n",
        "        except KeyboardInterrupt:\n",
        "            # Save on Ctrl+C\n",
        "            if conversation_history:\n",
        "                topics = extract_topics(conversation_history)\n",
        "                session_data = {\n",
        "                    'date': datetime.now().strftime(\"%Y-%m-%d %H:%M\"),\n",
        "                    'messages_count': len(conversation_history),\n",
        "                    'topics': topics\n",
        "                }\n",
        "                training_history.append(session_data)\n",
        "                save_history(training_history)\n",
        "                print(f\"\\n\\n✅ Session saved! ({len(conversation_history)} messages)\")\n",
        "            print(\"\\nCoach: Keep training! 💪\")\n",
        "            break\n",
        "\n",
        "        except Exception as e:\n",
        "            print(f\"\\n❌ Error: {str(e)}\")\n",
        "            print(\"(Make sure your API key is set: export GOOGLE_API_KEY='your_key_here')\\n\")\n",
        "            continue\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ],
      "metadata": {
        "collapsed": true,
        "id": "ivs9kj-13IMz"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}